EvolutionX-Android-16:
  kernel:
    - git clone https://github.com/Evolution-X-Devices/kernel_samsung_a71.git -b sixteen
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 a71_defconfig
  build:
    - ARCH=arm64 LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip PATH="${PWD}/clang/bin:$PATH" make -j$(nproc --all) O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - a71
  kernelSU:
    - stable-pin


Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status


# Stable-pin version of KernelSU is used by KernelSU.sh to replace placeholder (kernelsu-version)
KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s kernelsu-version
    stable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
    unstable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main


AnyKernel3:
  version:
    a71:
      - git clone https://github.com/HowWof/AnyKernel3.git -b master
    test:
      - echo "Test Success!"
